### ISSUE TITLE
Special characters in beakerlib phase name breaks results

### ISSUE THREAD

**Issue by vkadlcik** [teemtee/tmt#3333] opened 2024-10-31 12:57 UTC
Test: https://src.fedoraproject.org/tests/annobin/blob/main/f/Regression/bz2022973-annobin-needs-to-be-taught-about
CLI used: ```tmt -c distro=rhel-10.0 -c arch=x86_64 run -av provision -h connect -g test-machine-name plans -n all_tests tests -n .```

tmt 1.38 (specifically, the 1.38.0-1.fc40 Fedora build of tmt) gets confused and ends up with "Invalid partial custom result". tmt 1.37 works fine.

In tmt 1.38's work directory, I found tmt-report-results.yaml which suggests that tmt didn't understood the beakerlib phases in the test (maybe because of slashes? just a speculation though) and missed the results completely:

```
  - name: "/Setup"
    result: "pass"
    end-time: "2024-10-31T12:09:51.559323+00:00"
  - name: "/PASS"
    result: "/tmp/tmp.noomgemrkj"
    end-time: "2024-10-31T12:09:51.766331+00:00"
  - name: "/Cleanup"
    result: "pass"
    end-time: "2024-10-31T12:09:52.227596+00:00"
```
CC: @seberm

**Comment by seberm** [comment] 2024-11-01 08:37
Hello @vkadlcik,
thanks for reporting the issue!

I've successfully reproduced the issue and problem is a slash `/` character **at the beggining** of the phase name as you correctly mentioned.

Reproducer:

```
rlJournalStart
    for i in /sbin/ldconfig /usr/sbin/ldconfig; do
        rlPhaseStartTest $i
            rlRun "echo val: ${i}"
        rlPhaseEnd
    done
rlJournalEnd


$ tmt -r ~/tmt-tests/issue3333 run -a report --how display -v
```

You should also put the phase name variable into quotation marks: `rlPhaseStartTest "$i"`. But this doesn't matter in your case (no spaces in the loop items).

You can workaround the problem by adding any alphanumeric character as prefix to phase name, e.g.:

```
rlJournalStart
    for i in /sbin/ldconfig /usr/sbin/ldconfig; do
        rlPhaseStartTest "test file: $i"
            rlRun "echo val: ${i}"
        rlPhaseEnd
    done
rlJournalEnd
```

I am still looking at why this is happening. All the slashes in the phase name get converted to dashes, even the first one. See the `rljClosePhase` or the `rlReport` in the beakerlib:
- https://github.com/beakerlib/beakerlib/blob/cfa801fb175fef1e47b8552d6cf6efcb51df7227/src/journal.sh#L681C33-L681C43
- https://github.com/beakerlib/beakerlib/blob/cfa801fb175fef1e47b8552d6cf6efcb51df7227/src/testing.sh#L1053

```
rlReport "$(echo "${name//[^[:alnum:]]/-}" | tr -s '-')" "$result" "$score" "$logfile"
```

```
$ name='/some/file'
$ echo "${name//[^[:alnum:]]/-}" | tr -s '-'
-some-file
```

Phase names get propagated correctly, the strange thing is that phase name value influences the result value. I think the phase name value with a dash at the beginning is somehow/somewhere interpreted as **argument**. The problem could also be somewhere in the `tmt-report-result` script.

I still need to take a closer look and find out why and where the temporary directory value comes from and why it's interpreted as the result value.

**Comment by seberm** [comment] 2024-11-01 09:36
So the problem is probably the getopts parsing in the `tmt-report-result` script.

Take this as an example, where the `'-s...'` is somehow interpreted as an argument:

```
$ TMT_TEST_DATA=./ ./tmt-report-result '-some-phase-name' 'pass' '/some/tmp/dir'

# Generates:
- name: "/pass"
  result: "/some/tmp/dir"
  end-time: "2024-11-01T08:58:57.233025+00:00"
```

This `tmt-report-result` call will generate **nothing** without an error:

```
$ TMT_TEST_DATA=./ ./tmt-report-result '-abcd-option' 'pass' '/some/tmp/dir'
```

This returns an error: `./tmt-report-result: illegal option -- n`:

```
$ TMT_TEST_DATA=./ ./tmt-report-result '-not-option' 'pass' '/some/tmp/dir'
```

The correct call of `tmt-report-result` script should probably be to use two dashes which would interpret the `'-some-phase-name'` as a **positional argument**:

```
$ TMT_TEST_DATA=./ ./tmt-report-result -- '-some-phase-name' 'pass' '/some/tmp/dir'

- name: "/-some-phase-name"
  result: "pass"
  end-time: "2024-11-01T09:31:06.241894+00:00"
```

And then we should also remove all the dashes from the beginning of the `TESTNAME` variable in `tmt-report-result` script:

```
while [[ ${TESTNAME:0:1} == '-' ]]; do
    TESTNAME="${TESTNAME:1}"
done
```

Any ideas?

**Comment by sopos** [comment] 2024-11-01 13:43
Well, it surely can be fixed on the beakerlib side. I'm also thinking is replacing the non-alphanumeric characters by `_` (underscore) instead of `-` (hyphen) wouldn't be better solution in the end.

**Comment by psss** [comment] 2024-11-01 16:18
> Well, it surely can be fixed on the beakerlib side.

Great! @seberm, could you please create a pull request?

> I'm wondering if replacing the non-alphanumeric characters by `_` (underscore) instead of `-` (hyphen) wouldn't be better solution in the end.

I would vote to keep dashes as they seems to me more readable.

**Comment by sopos** [comment] 2024-11-01 19:43
to the speed of the beakerlib release
* it will be in the packit once the PR is merged
* Fedora updates take like 7-14 days, including EPEL
* internal beaker repo updates take quite a long time

**Comment by seberm** [comment] 2024-11-02 22:52
> Great! @seberm, could you please create a pull request?

Sure @psss : 
- https://github.com/beakerlib/beakerlib/pull/184

I've tried to use `${TESTNAME##*(-)}` (and some similar expressions) but it seems it's not working as expected. That's why I've used the `sed 's/^-\+//'`.

**Comment by seberm** [comment] 2024-11-04 19:35
I've tested the changes in https://github.com/beakerlib/beakerlib/pull/184 by creating a fedora VM in 1minutetip and manually changing `/usr/share/beakerlib/journal.sh` file. Everything seems to be working fine:

```
$ python -m tmt -r ~/tmt-learning/issue3333 run -av provision -h connect -g <vm-ip-address> -u root -p <pwd>
...
    report                               
        how: display                                    
            pass /tests/bkr-test                     
                pass /sbin-ldconfig                 
                pass /usr-sbin-ldconfig               
        summary: 1 test passed
...
```

```
$ cat tmt-report-results.yaml
  - name: "/sbin-ldconfig"
    result: "pass"
    end-time: "2024-11-04T19:30:49.185402+00:00"
  - name: "/usr-sbin-ldconfig"
    result: "pass"
    end-time: "2024-11-04T19:30:49.306138+00:00"
```

```
$ cat results.yaml
...
    subresult:
      - name: /sbin-ldconfig
        result: pass
        original-result: pass
        note:
        log: []
        start-time:
        end-time: '2024-11-04T19:30:49.185402+00:00'
        duration:
        check: []
        __class__:
            module: tmt.result
            name: SubResult
      - name: /usr-sbin-ldconfig
        result: pass
        original-result: pass
        note:
        log: []
        start-time:
        end-time: '2024-11-04T19:30:49.306138+00:00'
        duration:
        check: []
        __class__:
            module: tmt.result
            name: SubResult
...
```

**Comment by seberm** [comment] 2024-11-07 11:59
@The-Mule Yes, basically all characters which **are not** in `[:alnum:]` set and are at the beginning of the phase name can cause these problems.

I'll expand the tests and I'll add more of these special chars. Thanks.

**Comment by sopos** [comment] 2024-11-07 12:35
The new beakerlib version 1.31.3 is already brewing. The bodhi updates [1] are being processed at this point.

1. https://bodhi.fedoraproject.org/updates/?search=beakerlib-1.31.3

**Closed** 2024-11-20 09:13 UTC
Labels: bug, priority | should, area | results
