### ISSUE TITLE
If repo doesn't have git or remote is missing `plans show -v` tracebacks

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/tmt#1773] opened 2023-01-04 09:26 UTC
If repo doesn't have git or remote is missing `plans show -v` tracebacks.

Reproducer
```bash

$ cd `mktemp -d`
$ tmt init
$ cat <<EOF > plan.fmf
execute:
    how: tmt
EOF
$ tmt pl show -v
     ....
     enabled true
     sources /tmp/tmp.81b1OhBvtW/plan.fmf
     <Traceback>
```

Traceback from 'fmf-id' call when git repo doesn't exist. Traceback is different if remote doesn't exist (run `git init` and do `tmt plans show -v` again)
```python
Traceback (most recent call last):
  File "/home/lzachar/.virtualenvs/tmt/bin/tmt", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lzachar/gits/tmt/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/.virtualenvs/tmt/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/gits/tmt/tmt/cli.py", line 728, in plans_show
    plan.show()
  File "/home/lzachar/gits/tmt/tmt/base.py", line 1392, in show
    self._show_additional_keys()
  File "/home/lzachar/gits/tmt/tmt/base.py", line 453, in _show_additional_keys
    self._fmf_id()
  File "/home/lzachar/gits/tmt/tmt/base.py", line 459, in _fmf_id
    self.fmf_id.to_minimal_dict()), key_color='magenta'))
    ^^^^^^^^^^^
  File "/home/lzachar/gits/tmt/tmt/base.py", line 469, in fmf_id
    return tmt.utils.fmf_id(self.name, self.node.root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/gits/tmt/tmt/utils.py", line 2253, in fmf_id
    def_branch = default_branch(git_root)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzachar/gits/tmt/tmt/utils.py", line 2390, in default_branch
    subprocess.run(
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: ''

```

**Comment by psss** [comment] 2023-01-18 12:30
This is a regression and should be fixed in `1.21`.

**Comment by idorax** [comment] 2023-01-18 14:08
If we run `git init`, and run `tmt plans show -v` again, it fails like:
```python
(tmt) huanli@kvm-01-guest02:foo2$ tmt plans show -v
/plan
                discover 
...<snip>...
                 sources /home/huanli/dev/1773/foo2/plan.fmf
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "/home/huanli/.virtualenvs/tmt/bin/tmt", line 20, in <module>
    tmt.cli.main()
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/cli.py", line 744, in plans_show
    plan.show()
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/base.py", line 1447, in show
    self._show_additional_keys()
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/base.py", line 462, in _show_additional_keys
    self._fmf_id()
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/base.py", line 468, in _fmf_id
    self.fmf_id.to_minimal_dict()), key_color='magenta'))
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/base.py", line 478, in fmf_id
    return tmt.utils.fmf_id(self.name, self.node.root)
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/utils.py", line 2230, in fmf_id
    def_branch = default_branch(git_root)
  File "/home/huanli/.virtualenvs/tmt/lib/python3.10/site-packages/tmt/utils.py", line 2370, in default_branch
    with open(head) as ref:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/huanli/dev/1773/foo2/.git/refs/remotes/origin/HEAD'
```

**Comment by psss** [comment] 2023-01-18 14:10
Yes, because there is no default branch. We should check for both: If the git repo is present and if the remote head is available.

**Comment by idorax** [comment] 2023-01-18 14:25
@psss, thanks for clarification! 

To fix this issue, we need to deal with two situations：
1. If the `git repo` does not exist, should return an empty string before invoking `subprocess.run(f'git remote set-head ...`;
2. If the `remote head` is unavailable, should return an empty string before opening it as well.

**Comment by lukaszachy** [comment] 2023-02-02 08:31
Didn't manage to merge into tmt-1.21, aiming for next one.

**Closed** 2023-03-02 15:28 UTC
Labels: plans, must
