### ISSUE TITLE
export to nitrate wrongly disables test cases

### ISSUE THREAD

**Issue by vkadlcik** [teemtee/tmt#1475] opened 2022-08-26 14:14 UTC
I have a ```CONFIRMED``` Nitrate test case with
```
[relevancy]
collection !defined: False
```
```tmt tests import``` translates the metadata to main.fmf with:
```
...
enabled: true
...
adjust:
  - enabled: false
    when: collection is not defined
    continue: false
...
```
So far so good. However when I export the test back to Nitrate (```tmt tests export --how nitrate .```) the test ends up with ```status=DISABLED```.

I believe it's because ```tmt tests export``` **interprets** ```main.fmf``` although it shouldn't. In this specific example it runs with an empty context, interprets ```adjust```, gets ```enabled=false``` and that is exported as ```status=DISABLED``` to Nitrate. ```tmt tests export``` should just **read** the metadata, not interpret, and export it.

As a workaround I can use ```tmt -c collection=whatever tests export --how nitrate .``` but this is a pretty limited method. Users have to check what's ending up in Nitrate and need to define various contexts for various test cases just for the sake of exporting, that's simply not practical.

Please note that end users' existing data can be affected, meaning wrongfully disabled test cases. I'm afraid this bug should be prioritized, TMT+Nitrate users notified and advised to re-export all their tests when a fix is available.

**Comment by vkadlcik** [comment] 2022-08-26 14:32
Forgot to mention the version: tmt-1.16.0-1.fc36.noarch

**Comment by psss** [comment] 2022-08-27 10:59
Hm, that's an interesting constellation. Let's try to fix in `1.17`. As for now, the context adjust is applied always, even for commands like `tmt test show`. We could turn it off for this specific case but I'm not sure if that would not break other cases. Another way could be to explicitly not disable test cases during `tmt test export` or possibly check the original unmodified test metadata for the `enabled` attribute. @lukaszachy, @hegerj, any suggestions here?

**Comment by lukaszachy** [comment] 2022-08-29 06:47
There is a lot of corner cases like this then. This one is for 'enabled by default and disabled by adjust' however one can have the other way around (it is up to user to decide which makes more sense), so ignoring context will not help.
If we skip disabling test then user will need to visit tcms manually after they set enabled:false in their tmt metadata.

How about checking if there is any 'enabled: true' possible (unmodified and adjust rules taken into the account)?

**Comment by hegerj** [comment] 2022-08-29 12:03
It's a long time since I've worked on tmt so forgive me if this is a basic question, but what role does `adjust` play in setting status of nitrate case? Shouldn't that be simple mapping of `enabled: true` == `CONFIRMED`?

**Comment by psss** [comment] 2022-08-29 12:18
> what role does `adjust` play in setting status of nitrate case?

Adjust rules can be used to modify any key if the test metadata, including `enabled`, which is this case. The test is enabled or disable based on the context.

**Comment by psss** [comment] 2022-08-29 12:20
> How about checking if there is any 'enabled: true' possible (unmodified and adjust rules taken into the account)?

You mean to check all `adjust` rules for the `enabled:true` decision? This seems reasonable to me: If the test is enabled under at least one `context` then it should be marked as `CONFIRMED` in Nitrate so that it is correctly picked by `wow` (and then further filtered based on the actual context).

**Comment by psss** [comment] 2022-08-29 12:22
> What about a simple means of enforcing `ENABLED`? Be it a CLI option...

A command line option overriding the detect status sounds ok as well. The solution could combine both.

**Comment by lukaszachy** [comment] 2022-08-29 13:15
CLI option is a problem. We need to make this more error prove - Imaging exporting with cli option and at some point in the future (by mistake) export whole repo -> BOOM, your test is disabled again.

The `enabled: true` might come from not adjusted or adjusted data. We should search through all. So "DISABLED" will be only test if there is no 'enabled: true' at all.

I'll try to do PR.

**Closed** 2022-08-29 22:03 UTC
Labels: export, nitrate

**Comment by vkadlcik** [comment] 2022-08-31 09:14
Works for me, thank you guys!
