### ISSUE TITLE
Plugin schema often lacks shared fields - name, where, order

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#3008] opened 2024-06-12 13:52 UTC
```
/plans/cut-8to9 
warn C000 key "upgrade-path" not recognized by schema /schemas/execute/tmt 
warn C000 key "url" not recognized by schema /schemas/execute/tmt 
warn C000 value of "how" is not "tmt" 
warn C000 key "name" not recognized by schema /schemas/execute/upgrade 
warn C000 fmf node failed schema validation
```

```
(dev) [pts-1:0]: happz@multivac [template-raise-an-error] ~/git/tmt $ l tmt/schemas/prepare/
total 20
drwxr-xr-x. 1 happz happz  114 Jun  3 11:31 .
drwxr-xr-x. 1 happz happz  206 Jun 10 21:30 ..
-rw-r--r--. 1 happz happz  273 Aug  7  2023 ansible.yaml
-rw-r--r--. 1 happz happz  664 Aug  7  2023 errata.yaml
-rw-r--r--. 1 happz happz  421 Apr 22 17:42 feature.yaml
-rw-r--r--. 1 happz happz 1019 Aug  7  2023 install.yaml
-rw-r--r--. 1 happz happz  265 Aug  7  2023 shell.yaml
(dev) [pts-1:0]: happz@multivac [template-raise-an-error] ~/git/tmt $ grep 'order' tmt/schemas/prepare/*
tmt/schemas/prepare/install.yaml:  order:
tmt/schemas/prepare/install.yaml:    $ref: "/schemas/core#/definitions/order"
(dev) [pts-1:0]: happz@multivac [template-raise-an-error] ~/git/tmt $ 
```

**Comment by psss** [comment] 2024-06-25 09:45
Looks like a duplicate of #2984.

**Closed** 2024-06-25 14:20 UTC
Labels: bug, schema
